#!/usr/bin/env bash

#-----------------------------------------------------------------------
# runserver
# Author: David Basili and Dane Jacobson
#-----------------------------------------------------------------------

python registrar.py "$@"

