#!/usr/bin/env bash

#--------------------------------------------------------------------
# regserver
# Authors: David Basili, Dane Jacobson
#--------------------------------------------------------------------

python regserver.py "$@"